version: "3.9"
services:
  web:
    build: .
    ports:
      - $FS_ARCHIVE_PORT:$FS_ARCHIVE_PORT
      - $FS_PASSCODE_PORT:$FS_PASSCODE_PORT
    volumes:
      - ./:/archive
      - ./:/logs
    environment:
      - FS_LOG_DIRECTORY
      - FS_ARCHIVE_DIRECTORY
      - FS_PASSCODE_PORT
      - FS_ARCHIVE_PORT
      - FS_SECRET
      - FS_HOST
