version: "3.9"
services:
  web:
    build: .
    ports:
      - $FS_ARCHIVE_PORT:$FS_ARCHIVE_PORT
      - $FS_PASSCODE_PORT:$FS_PASSCODE_PORT
    volumes:
      - $LOCAL_ARCHIVE_DIRECTORY/:$FS_ARCHIVE_DIRECTORY
      - $LOCAL_LOG_DIRECTORY:$FS_LOG_DIRECTORY
    environment:
      - FS_LOG_DIRECTORY
      - FS_ARCHIVE_DIRECTORY
      - FS_PASSCODE_PORT
      - FS_ARCHIVE_PORT
      - FS_SECRET
      - FS_HOST
  frontend:
    build: ./file-server-frontend
    ports: [80:80]
